perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr10.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr11.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr12.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr13.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr14.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr15.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr16.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr17.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr18.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr19.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr1.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr20.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr21.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr22.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr2.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr3.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr4.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr5.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr6.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr7.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr8.diploid.sperms.snp.strict.filter
perl ../bin/infer_diploid_haplotype.pl --minlinks 10 --linkratio 0.2 --minblock  10 chr9.diploid.sperms.snp.strict.filter
