perl ../bin/phase_more_by_sperm.pl chr10.diploid.sperms.snp.strict.filter.haplo chr10.diploid.sperms.snp > chr10.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr11.diploid.sperms.snp.strict.filter.haplo chr11.diploid.sperms.snp > chr11.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr12.diploid.sperms.snp.strict.filter.haplo chr12.diploid.sperms.snp > chr12.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr13.diploid.sperms.snp.strict.filter.haplo chr13.diploid.sperms.snp > chr13.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr14.diploid.sperms.snp.strict.filter.haplo chr14.diploid.sperms.snp > chr14.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr15.diploid.sperms.snp.strict.filter.haplo chr15.diploid.sperms.snp > chr15.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr16.diploid.sperms.snp.strict.filter.haplo chr16.diploid.sperms.snp > chr16.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr17.diploid.sperms.snp.strict.filter.haplo chr17.diploid.sperms.snp > chr17.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr18.diploid.sperms.snp.strict.filter.haplo chr18.diploid.sperms.snp > chr18.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr19.diploid.sperms.snp.strict.filter.haplo chr19.diploid.sperms.snp > chr19.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr1.diploid.sperms.snp.strict.filter.haplo chr1.diploid.sperms.snp > chr1.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr20.diploid.sperms.snp.strict.filter.haplo chr20.diploid.sperms.snp > chr20.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr21.diploid.sperms.snp.strict.filter.haplo chr21.diploid.sperms.snp > chr21.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr22.diploid.sperms.snp.strict.filter.haplo chr22.diploid.sperms.snp > chr22.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr2.diploid.sperms.snp.strict.filter.haplo chr2.diploid.sperms.snp > chr2.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr3.diploid.sperms.snp.strict.filter.haplo chr3.diploid.sperms.snp > chr3.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr4.diploid.sperms.snp.strict.filter.haplo chr4.diploid.sperms.snp > chr4.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr5.diploid.sperms.snp.strict.filter.haplo chr5.diploid.sperms.snp > chr5.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr6.diploid.sperms.snp.strict.filter.haplo chr6.diploid.sperms.snp > chr6.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr7.diploid.sperms.snp.strict.filter.haplo chr7.diploid.sperms.snp > chr7.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr8.diploid.sperms.snp.strict.filter.haplo chr8.diploid.sperms.snp > chr8.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chr9.diploid.sperms.snp.strict.filter.haplo chr9.diploid.sperms.snp > chr9.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chrX.diploid.sperms.snp.strict.filter.haplo chrX.diploid.sperms.snp > chrX.diploid.sperms.snp.strict.filter.haplo.more
perl ../bin/phase_more_by_sperm.pl chrY.diploid.sperms.snp.strict.filter.haplo chrY.diploid.sperms.snp > chrY.diploid.sperms.snp.strict.filter.haplo.more
