#!/bin/sh

# simout.bam is generated by bwa.kit referenced with hg38. The chrHBV are not mapped.

scripts/pre_process.pl -s 20 -k 1500 -q 0 -t 8 -b merged/simout.bam -I hg18/HomoGRCh38 -A hg18/HomoGRCh38.fa.fai
scripts/meerkat.pl -d 5 -s 20 -p 5 -o 3 -t 8 -b merged/simout.bam -F hg18/ -S samtools-0.1.20/
scripts/mechanism.pl -b merged/simout.bam -R hg18rmsk/rmsk-hg18.txt

