#!/bin/bash
###
#PBS -S /bin/bash
#PBS -N VirusFinder-simulation
#PBS -d /scratch/kingw/VirusFinder/simulation
#PBS -o /scratch/kingw/VirusFinder/simulation/VirusFinder_output.txt
#PBS -V
#PBS -l nodes=1:ppn=8
#PBS -l mem=25000mb
#PBS -l walltime=10:00:00
#PBS -j oe
#PBS -M qingguo.wang@vanderbilt.edu
#PBS -m bae


perl /scratch/kingw/bin/VirusFinder/VirusFinder.pl  -c template-config.txt 
