#PROG=../bin/mvicuna
PROG = ../bin/alnmethly

COMPILER=g++ 
FLAGs=-std=c++0x
OMP=-fopenmp

all:
	-mkdir ../bin
	$(COMPILER) $(OMP) $(FLAGs) -O3 *.cpp -o $(PROG)
	-ln -s ../t.pl ../bin

clean:
	rm -rf $(PROG)
	rm -fr ../bin/
