<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Bioseq</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#bioseq-DNA</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#bioseq-RNA</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#bioseq-gaps</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>\b[ATCGatcgNnUu*\-?]+\b</string>
			<key>name</key>
			<string>markup.bioseq.NA</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#bioseq-Protein</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#bioseq-gaps</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b[A-Z*\-?]+\b</string>
			<key>name</key>
			<string>markup.bioseq.AA</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bioseq-DNA</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)A</string>
					<key>name</key>
					<string>markup.bioseq.base.A</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[Tt]</string>
					<key>name</key>
					<string>markup.bioseq.base.T</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[Cc]</string>
					<key>name</key>
					<string>markup.bioseq.base.C</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[Gg]</string>
					<key>name</key>
					<string>markup.bioseq.base.G</string>
				</dict>
			</array>
		</dict>
		<key>bioseq-Protein</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)[NDB]</string>
					<key>name</key>
					<string>markup.bioseq.aa.Aromatic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)[RHK]</string>
					<key>name</key>
					<string>markup.bioseq.aa.Basic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)[ACGILMFPWVJ]</string>
					<key>name</key>
					<string>markup.bioseq.aa.Nonpolar</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)[QSTY]</string>
					<key>name</key>
					<string>markup.bioseq.aa.Polar</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)[DE]</string>
					<key>name</key>
					<string>markup.bioseq.aa.Acidic</string>
				</dict>
			</array>
		</dict>
		<key>bioseq-RNA</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[Uu]</string>
					<key>name</key>
					<string>markup.bioseq.base.U</string>
				</dict>
			</array>
		</dict>
		<key>bioseq-gaps</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[*\-?]</string>
					<key>name</key>
					<string>markup.bioseq.other</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.bioseq</string>
	<key>uuid</key>
	<string>644BDC2C-2E5C-47CF-91AE-AD9BEBAFE023</string>
</dict>
</plist>
