<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fasta</string>
		<string>fa</string>
		<string>dna</string>
	</array>
	<key>firstLineMatch</key>
	<string>^&gt;(.*)</string>
	<key>name</key>
	<string>FASTA</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.bioseq</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\&gt;(.+)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.bioseq.Title.DNA</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.bioseq.FASTA.NA</string>
			<key>while</key>
			<string>(?i)^[ATCGUN*\-?]+$</string>
			<key>whileCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.bioseq</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\&gt;(.+)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.bioseq.Title.AA</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.bioseq.FASTA.AA</string>
			<key>while</key>
			<string>(?i)^[A-Z*\-?]+$</string>
			<key>whileCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.bioseq</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fasta</string>
	<key>uuid</key>
	<string>F44460F6-8239-44C7-8A61-6F59BE248319</string>
</dict>
</plist>
