<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fasta</string>
		<string>fa</string>
		<string>dna</string>
	</array>
	<key>firstLineMatch</key>
	<string>^&gt;(.*)</string>
	<key>name</key>
	<string>FASTA</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>?&lt;A&gt;^\&gt;(.+)\n</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.bioseq.Title.DNA</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;A&gt;?!\G)</string>
			<key>name</key>
			<string>markup.bioseq.FASTA.DNA</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#bioseq-DNA</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>match</key>
					<string>[ATCG]+</string>
					<key>name</key>
					<string>markup.seq.DNA</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\&gt;(.+)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.bioseq.Title.RNA</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.bioseq.FASTA.RNA</string>
			<key>while</key>
			<string>^[AUCGaucgNn*-?]+$</string>
			<key>whileCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#bioseq-DNA</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#bioseq-RNA</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#bioseq-gaps</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\&gt;(.+)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.bioseq.Title.Protein</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.bioseq.FASTA.Protein</string>
			<key>while</key>
			<string>^[ABCDEFGHIJKLMNOPQRSTUVWXYZ*-?]+$</string>
			<key>whileCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#bioseq-Protein</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#bioseq-gaps</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bioseq-DNA</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[Aa]</string>
					<key>name</key>
					<string>markup.bioseq.base.A</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[Tt]</string>
					<key>name</key>
					<string>markup.bioseq.base.T</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[Cc]</string>
					<key>name</key>
					<string>markup.bioseq.base.C</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[Gg]</string>
					<key>name</key>
					<string>markup.bioseq.base.G</string>
				</dict>
			</array>
		</dict>
		<key>bioseq-Protein</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[ND]</string>
					<key>name</key>
					<string>markup.bioseq.aa.Aromatic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[ABCDEFGHIJKLMNOPQRSUVWXY]</string>
					<key>name</key>
					<string>markup.bioseq.aa.Basic</string>
				</dict>
			</array>
		</dict>
		<key>bioseq-RNA</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[Uu]</string>
					<key>name</key>
					<string>markup.bioseq.base.U</string>
				</dict>
			</array>
		</dict>
		<key>bioseq-gaps</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[*-?]</string>
					<key>name</key>
					<string>markup.bioseq.other</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.fasta</string>
	<key>uuid</key>
	<string>F44460F6-8239-44C7-8A61-6F59BE248319</string>
</dict>
</plist>
