#!/usr/bin/env perl
use strict;
use warnings;
use File::Spec::Functions qw(catfile);

my @loaded = grep {
    eval "require $_";
    !$@ ? 1 : ($@ =~ s/\(\@INC contains: \Q@INC\E\)//, warn("Failed lo
+ading $_: $@"), 0);
} @ARGV;

my @pm = map catfile(split '::') . (/\.pm\z/ ? '' : '.pm'), @loaded;

print "@INC{@pm}\n";

__END__
http://www.perlmonks.org/?node=whichpm
http://search.cpan.org/~jkutej/App-whichpm-0.04/script/whichpm

For Version info.:
alias modver="perl -e\"eval qq{use \\\$ARGV[0];\\\\\\\$v=\\\\\\\$\\\${ARGV[0]}::VERSION;};\ print\\\$@?qq{No module found\\n}:\\\$v?qq{Version \\\$v\\n}:qq{Found.\\n};\"\$1"

$ whichpm File::Spec::Functions
/System/Library/Perl/5.18/darwin-thread-multi-2level/File/Spec/Functions.pm

$ modver File::Spec::Functions
Version 3.40
