#!/bin/bash
#$ -S /bin/bash
#$ -q fgi.q -P fgi
#$ -N p0cut
#$ -l vf=600M,num_proc=2
#$ -binding linear:3
#$ -cwd -r y
#$ -v PERL5LIB,PATH,LD_LIBRARY_PATH
#$ -e /dev/null -o /dev/null

#$ -t 1-155
INFILE=`sed -n "${SGE_TASK_ID}p" fq0.lst`
read -ra INDAT <<<"$INFILE"

SEADAPTERSTR='-g GAACGACATGGCTACGATCCGACTT -a AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA'
PEADAPTERSTR="$SEADAPTERSTR -A AAGTCGGATCGTAGCCATGTCGTTC -G TTGTCTTCCTAAGACCGCTTGGCCTCCGACTT"
IONSEADAPTERSTR='-g CCACTACGCCTCCGCTTTCCTCTCTATGGGCAGTCGGTGAT -a ATCnnnnnnnnnnCTGAGTCGGAGACACGCAGGGATGAGATGGTT'
IONPEADAPTERSTR="$IONSEADAPTERSTR -G CCATCTCATCCCTGCGTGTCTCCGACTCAGnnnnnnnnnnGAT -A ATCACCGACTGCCCATAGAGAGGAAAGCGGAGGCGTAGTGGTT"
HISEQSEADAPTERSTR='-g AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT -a AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATC -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCACnnnnnnnnATCTCGTATGCCGTCTTCTGCTTG'
HISEQPEADAPTERSTR="$HISEQSEADAPTERSTR -G GATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT -G CAAGCAGAAGACGGCATACGAGATnnnnnnnnGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT"

mkdir fq

cutadapt -j 2 -m 1 -O 6 -n 2 $HISEQSEADAPTERSTR -o fq/${INDAT[0]} raw/${INDAT[0]} >fq/${INDAT[0]}.log
