#!/bin/env perl
use strict;
use warnings;
use File::Spec::Functions qw(catfile);

my @loaded = grep {
    eval "require $_";
    !$@ ? 1 : ($@ =~ s/\(\@INC contains: \Q@INC\E\)//, warn("Failed lo
+ading $_: $@"), 0);
} @ARGV;

my @pm = map catfile(split '::') . (/\.pm\z/ ? '' : '.pm'), @loaded;

print "@INC{@pm}\n";

__END__
http://www.perlmonks.org/?node=whichpm
http://search.cpan.org/~jkutej/App-whichpm-0.04/script/whichpm

