IgnorePath '/etc/adjtime'
IgnorePath '/etc/fstab'
IgnorePath '/etc/group*'
IgnorePath '/etc/gshadow*'
IgnorePath '/etc/passwd*'
IgnorePath '/etc/shadow*'
IgnorePath '/etc/xml/catalog'
IgnorePath '/etc/resolv.conf'
IgnorePath '/etc/*.bak'
IgnorePath '/etc/shells'
IgnorePath '__pycache__'
IgnorePath '/etc/.pwd.lock'
IgnorePath '/etc/dconf/db/*'
IgnorePath '/usr/lib/locale/locale-archive'

