# Packages common in all profiles
AddPackage base
AddPackage intel-ucode
#AddPackage amd-ucode
AddPackage artix-grub-theme
AddPackage artix-branding-base

AddPackage elogind-dinit
AddPackage acpi
AddPackage acpid-dinit
AddPackage alsa-firmware
AddPackage alsa-utils-dinit
AddPackage avahi-dinit
AddPackage b43-fwcutter
AddPackage bluez-dinit
AddPackage btrfs-progs
AddPackage crda
AddPackage cronie-dinit
AddPackage cryptsetup-dinit
AddPackage dhclient
AddPackage dhcpcd-dinit
AddPackage diffutils
AddPackage dmraid
AddPackage dosfstools
AddPackage e2fsprogs
AddPackage ecryptfs-utils
AddPackage efibootmgr
AddPackage exfat-utils
AddPackage f2fs-tools
AddPackage grub
AddPackage haveged-dinit
AddPackage inetutils
AddPackage iptables
AddPackage ipw2100-fw
AddPackage ipw2200-fw
AddPackage jfsutils
#AddPackage linux
#AddPackage linux-firmware
#AddPackage linux-headers
AddPackage lsb-release
AddPackage logrotate
AddPackage lsb-release
AddPackage lvm2-dinit
AddPackage man-db
AddPackage man-pages
AddPackage mdadm-dinit
AddPackage memtest86+
AddPackage mkinitcpio
AddPackage mkinitcpio-openswap
AddPackage modemmanager
AddPackage nano
AddPackage nbd
AddPackage net-tools
AddPackage nfs-utils-dinit
AddPackage ntfs-3g
AddPackage ntp-dinit
AddPackage openssh-dinit
AddPackage os-prober
AddPackage reiserfsprogs
AddPackage rsync-dinit
AddPackage s-nail
AddPackage sudo
AddPackage sysfsutils
AddPackage texinfo
AddPackage usbutils
AddPackage vi
AddPackage which
AddPackage wpa_supplicant-dinit
AddPackage xfsprogs
AddPackage zsh
