[project]
name = "FstFOVglobalCoord"
version = "0.1.0"
description = "Add a short description here"
authors = ["HU Xuesong <87519979+huxs001@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64"]

[tasks]

[dependencies]

[host-dependencies]
libuv = ">=1.48"
zlib-ng = ">=2.2.1,<2.3"
llvm-openmp = ">=18.1"
isa-l = ">=2.31"
xopen = ">=2.0.2,<3"

[build-dependencies]
pkg-config = ">=0.29"
lld = ">=18.1"
clang = ">=18.1"

[target.linux-64.build-dependencies]
kernel-headers_linux-64 = ">=4.18"
gcc = ">=14"
llvmdev = ">=18.1"
clangdev = ">=18.1"

[target.osx-64.build-dependencies]
#clang = ">=18"
