ifndef CFG_MK
HELPERS_MK=cfg.mk

FQ_PATH:=~/work/tiger/fq.p ~/work/tiger/fq.f

ADAPTER13:=AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
ADAPTER15:=ACACTCTTTCCCTACACGACGCTCTTCCGATCT
ADAPTER23:=AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
ADAPTER25:=GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT

CUTADAPTARG:=-e 0.08 -n 2 -m 0 -O 5

endif
